name: CI

on:
  pull_request:
  push:
      branches:
      - master

jobs:
  mix_espec:
    name: mix espec (Erlang/OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})
    runs-on: ubuntu-latest
    container: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-alpine-3.11.6
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.8.2
            otp: 20.3.8.26
          - elixir: 1.9.4
            otp: 20.3.8.26
          - elixir: 1.10.3
            otp: 21.3.8.16
          - elixir: 1.10.3
            otp: 23.0.2
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: mix espec
        env:
          MIX_ENV: test

  check_formatted:
    name: Check formatted
    runs-on: ubuntu-latest
    container: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-alpine-3.11.6
    strategy:
      matrix:
        include:
          - elixir: 1.10.3
            otp: 23.0.2
    steps:
      - uses: actions/checkout@v2.3.1
      - run: mix format --check-formatted
